# Generated by Django 5.1.4 on 2025-02-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('P', 'POKEMON'), ('S', 'SUPPORTER'), ('I', 'ITEM'), ('T', 'TOOL'), ('F', 'FOSSIL')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('effect', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('inputs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C', 'COLORLESS'), ('FR', 'FIRE'), ('W', 'WATER'), ('L', 'LIGHTNING'), ('G', 'GRASS'), ('FG', 'FIGHTING'), ('P', 'PSYCHIC'), ('DA', 'DARKNESS'), ('M', 'METAL'), ('DR', 'DRAGON'), ('FA', 'FAIRY')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('text', models.TextField()),
                ('trigger', models.CharField()),
                ('effects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_effect', to='pokemon_game_api.effect')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('attack_text', models.TextField()),
                ('damage_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_effect', to='pokemon_game_api.effect')),
                ('effects', models.ManyToManyField(to='pokemon_game_api.effect')),
                ('energy_cost', models.ManyToManyField(to='pokemon_game_api.energycost')),
            ],
        ),
        migrations.AddField(
            model_name='energycost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_game_api.energytype'),
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_game_api.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('N', 'NORMAL'), ('FR', 'FIRE'), ('W', 'WATER'), ('E', 'ELECTRIC'), ('GA', 'GRASS'), ('FG', 'FIGHTING'), ('PS', 'PSYCHIC'), ('DA', 'DARK'), ('S', 'STEEL'), ('DR', 'DRAGON'), ('FA', 'FAIRY'), ('I', 'ICE'), ('GO', 'GROUND'), ('FL', 'FLYING'), ('PO', 'POISON'), ('B', 'BUG'), ('R', 'ROCK'), ('GH', 'GHOST')], max_length=2, unique=True)),
                ('default_resistance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_resistance', to='pokemon_game_api.energytype')),
                ('default_weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_weakness', to='pokemon_game_api.energytype')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_game_api.energytype')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('retreat_cost', models.IntegerField()),
                ('level', models.IntegerField()),
                ('abilities', models.ManyToManyField(to='pokemon_game_api.ability')),
                ('attacks', models.ManyToManyField(to='pokemon_game_api.attack')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_game_api.pokemon')),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_game_api.pokemontype')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='default_types',
            field=models.ManyToManyField(to='pokemon_game_api.pokemontype'),
        ),
        migrations.AddField(
            model_name='attack',
            name='attack_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_effect', to='pokemon_game_api.pokemontype'),
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=20)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance', to='pokemon_game_api.energytype')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('text', models.CharField()),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_game_api.cardtype')),
                ('effects', models.ManyToManyField(related_name='trainer_effect', to='pokemon_game_api.effect')),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=20)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakness', to='pokemon_game_api.energytype')),
            ],
        ),
    ]
