# Generated by Django 5.1.4 on 2025-02-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_game_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='card_type',
            field=models.CharField(choices=[('P', 'POKEMON'), ('S', 'SUPPORTER'), ('I', 'ITEM'), ('T', 'TOOL'), ('F', 'FOSSIL')], max_length=2, unique=True),
        ),
    ]
