# Generated by Django 5.1.4 on 2025-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_game_api', '0002_alter_cardtype_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='card_type',
            field=models.CharField(choices=[('0', 'POKEMON'), ('1', 'SUPPORTER'), ('2', 'ITEM'), ('3', 'TOOL'), ('4', 'FOSSIL')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='energytype',
            name='name',
            field=models.CharField(choices=[('0', 'COLORLESS'), ('1', 'FIRE'), ('2', 'WATER'), ('3', 'LIGHTNING'), ('4', 'GRASS'), ('5', 'FIGHTING'), ('6', 'PSYCHIC'), ('7', 'DARKNESS'), ('8', 'METAL'), ('9', 'DRAGON'), ('10', 'FAIRY')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(choices=[('0', 'NORMAL'), ('1', 'FIRE'), ('2', 'WATER'), ('3', 'ELECTRIC'), ('4', 'GRASS'), ('5', 'FIGHTING'), ('6', 'PSYCHIC'), ('7', 'DARK'), ('8', 'STEEL'), ('9', 'DRAGON'), ('10', 'FAIRY'), ('11', 'ICE'), ('12', 'GROUND'), ('13', 'FLYING'), ('14', 'POISON'), ('15', 'BUG'), ('16', 'ROCK'), ('17', 'GHOST')], max_length=2, unique=True),
        ),
    ]
