# Generated by Django 5.1.4 on 2025-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_game_api', '0003_alter_cardtype_card_type_alter_energytype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='card_type',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='energytype',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
